# Generated by Django 6.0 on 2026-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_migrate_data_and_remove_old_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_linkedin_url_de',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_linkedin_url_en',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_linkedin_url_ta',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_name_de',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='company_name_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='company_name_ta',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
