# Generated by Django 6.0 on 2025-12-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_add_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hero_statement_en',
            field=models.CharField(blank=True, help_text="A short tagline or statement (e.g., 'Passionate developer building amazing things')", max_length=255),
        ),
    ]
