# Generated by Django 6.0 on 2025-12-19 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_make_hero_statement_optional'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Category identifier (e.g., 'about-me', 'cpp-developer')", unique=True)),
                ('category_type', models.CharField(choices=[('special', 'Special Category'), ('skill', 'Skill Category')], default='special', max_length=10)),
                ('name_en', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100)),
                ('name_ta', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Icon emoji or identifier', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order in navigation')),
                ('skill_category', models.ForeignKey(blank=True, help_text='Link to SkillCategory if this is a skill-based category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.skillcategory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select which categories this profile should be displayed for', related_name='profiles', to='profiles.category'),
        ),
    ]
