# Generated by Django 6.0 on 2025-12-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_create_initial_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='skill_category',
        ),
        migrations.AddField(
            model_name='category',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills text to display in console when this category is selected. Use bullet points or plain text.'),
        ),
    ]
